# Website title & description (the description is used in the HTML <head>, read by Google and co)
title: Firstname Lastname
description: >
  Write a short bio. The above ">" allows to have multiple lines here.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget dolor
  venenatis massa sodales tincidunt ac nec erat. Aenean fermentum erat eget
  dapibus pulvinar. Mauris diam odio, sagittis ut odio eget.


# Your personal infos (used for the sidebar)
author:
  # Site title
  name: Firstname Lastname
  description: Job title
  photo: /images/photo.jpg
  # Contacts (will be used by the contact block, you can enter everything here and choose which one should appear there)
  email: firstname.lastname@lip6.fr
  phone: 01 23 45 67 89
  address: "Couloir 26-00, Bureau 525 \n 4, place Jussieu \n 75005 Paris \n France"
  twitter: username
  linkedin: username
  github: username
  google-plus: username


# Link that appear at the top of the sidebar to return to the "main" site of the team, remove lines below to remove link
back-link:
  url: http://webia.lip6.fr/~cord
  title: Multimedia team


# Technical infos
baseurl: "/~username" # url of your webpage if not at the root of the domain (leading /, no trailing /)
url: "http://webia.lip6.fr" # the base hostname & protocol for your site (no trailing /)
header-default-style: trianglify # default page header style (see styles in user documentation)
# google-analytics: UA-XXXXXXX-X # your google analytics code if you want visit stats (uncomment to enter)


# "Very" technical infos (modify only if you know what you're doing)
sass:
  sass_dir: /assets/css/
  style: compressed
timezone: Europe/Paris
include: ['_pages']
permalink: /:title/
collections:
  - homepage
onepage-default-collection: homepage
defaults:
  # default layout for pages is "page", and link is only filename without "_pages/"
  - scope:
      path: _pages
    values:
      order: 50 # Default order value at 50 so that you can force some pages to appear at the end without setting the order for all of them
      layout: page
      permalink: /:basename/
  # default layout for homepage blocks is "onepage-block"
  - scope:
      type: homepage
    values:
      layout: onepage-block
