# Website title & description (the description is used in the HTML <head>, read by Google and co)
title: Matthieu Cord
description: >
  Professor at UPMC-Sorbonnes Universités. Researcher at LIP6 on Image Processing, Computer Vision, Deep Learning, Pattern Recognition and Computational Cooking


# Your personal infos (used for the sidebar)
author:
  # Site title
  name: Matthieu Cord
  description: Professor at UPMC - Sorbonne Universities, Researcher at LIP6 UPMC & CNRS
  photo: /images/photo.png
  # Contacts (will be used by the contact block, you can enter everything here and choose which one should appear there)
  email: matthieu.cord@lip6.fr
  phone: "(+33) 1 44 27 71 39 \n <small>Fax: (+33) 1 44 27 70 00</small>"
  address: "LIP6 / UPMC \n 4, place Jussieu \n 75005 Paris, France \n <a class=\"btn btn-default\" href=\"https://www.lip6.fr/informations/comment.php?LANG=en\">Directions</a>"


# Technical infos
baseurl: "/~robert/cord" # url of your webpage if not at the root of the domain (leading /, no trailing /)
url: "http://webia.lip6.fr" # the base hostname & protocol for your site (no trailing /)
header-default-style: trianglify # default page header style (see styles in user documentation)
# google-analytics: UA-XXXXXXX-X # your google analytics code if you want visit stats (uncomment to enter)


# "Very" technical infos (modify only if you know what you're doing)
sass:
  sass_dir: /assets/css/
  #style: compressed
timezone: Europe/Paris
include: ['_pages']
permalink: /:title/
collections:
  - homepage
onepage-default-collection: homepage
defaults:
  # default layout for pages is "page", and link is only filename without "_pages/"
  - scope:
      path: _pages
    values:
      order: 50 # Default order value at 50 so that you can force some pages to appear at the end without setting the order for all of them
      layout: page
      permalink: /:basename/
  # default layout for homepage blocks is "onepage-block"
  - scope:
      type: homepage
    values:
      layout: onepage-block
